bhuriyo/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mysite.urls'))
]

mysite/urls.py
from django.urls import path, include

from . import views
from django.conf import settings
from django.conf.urls.static import static
app_name = 'mysite'


urlpatterns = [
    path('', views.index, name='index'),
    path('contact', views.contact, name="contact"),
    path('about-us', views.about, name="about-us"),
    path('blog', views.blog, name="blog"),
    path('portfolio', views.portfolio, name="portfolio"),
    path('blog/<int:id>', views.blog_detail, name="blog-detail")

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/models.py
from django.db import models

# Create your models here.
from django.db import models
from django.utils import timezone
from tinymce.models import HTMLField
from sorl.thumbnail import ImageField
from preferences.models import Preferences


class CMSPage(models.Model):

    def __str__(self):
        return self.title

    CMS_STATUS = ((1, 'Active'), (0, 'Inactive'))

    title = models.CharField(max_length=255)
    slug = models.CharField(max_length=255, unique=True)
    description = HTMLField()
    status = models.PositiveSmallIntegerField(choices=CMS_STATUS, default=1)


class Blog(models.Model):

    def __str__(self):
        return self.title

    BLOG_STATUS = ((1, 'Active'), (0, 'Inactive'))

    title = models.CharField(max_length=255)
    description = HTMLField()
    image = ImageField(upload_to='blog')
    status = models.PositiveSmallIntegerField(choices=BLOG_STATUS, default=1)
    published_date = models.DateTimeField(auto_now_add=True, blank=True)


class PortfolioCategory(models.Model):

    def __str__(self):
        return self.title

    PORTFOLIO_CATEGORY_STATUS = ((1, 'Active'), (0, 'Inactive'))
    title = models.CharField(max_length=255)
    status = models.PositiveSmallIntegerField(choices=PORTFOLIO_CATEGORY_STATUS, default=1)
    published_date = models.DateTimeField(auto_now_add=True, blank=True)


class Portfolio(models.Model):

    def __str__(self):
        return self.title

    PORTFOLIO_STATUS = ((1, 'Active'), (0, 'Inactive'))
    title = models.CharField(max_length=255)
    description = HTMLField()
    image = ImageField(upload_to='portfolio')
    url = models.CharField(max_length=255)
    category = models.ForeignKey(PortfolioCategory, default=1, on_delete=models.SET_DEFAULT)
    status = models.PositiveSmallIntegerField(choices=PORTFOLIO_STATUS, default=1)
    published_date = models.DateTimeField(auto_now_add=True, blank=True)


class Testimonial(models.Model):

    def __str__(self):
        return self.title

    TESTIMONIAL_STATUS = ((1, 'Active'), (0, 'Inactive'))
    title = models.CharField(max_length=255)
    position = models.CharField(max_length=255)
    description = HTMLField()
    image = models.ImageField(upload_to='testimonial')
    status = models.PositiveSmallIntegerField(choices=TESTIMONIAL_STATUS, default=1)
    published_date = models.DateTimeField(auto_now_add=True, blank=True)


class MyPreferences(Preferences):
    portal_contact_home_about = HTMLField()
    portal_contact_email = models.EmailField()
    portal_contact_phone = models.CharField(max_length=255)
    portal_contact_address = models.TextField()
    portal_contact_facebook = models.CharField(max_length=255)
    portal_contact_instagram = models.CharField(max_length=255)
    portal_contact_twitter = models.CharField(max_length=255)

mysite/views.py
from django.shortcuts import render

# Create your views here.

from django.shortcuts import get_object_or_404, render
# Create your views here.
from django.http import HttpResponse, JsonResponse
from django.template import loader
from .models import CMSPage, PortfolioCategory, Portfolio, Testimonial, Blog
from django.http import Http404
from django.http import HttpResponseRedirect
from django.urls import reverse
from preferences import preferences
from django.core.mail import EmailMessage


def index(request):

    about_us = CMSPage.objects.filter(slug='about_us')[:1]
    portfolio = Portfolio.objects.filter()[:5]
    testimonial = Testimonial.objects.filter()[:3]
    blogs = Blog.objects.filter()[:3]
    context = {'about_us': about_us, 'portfolio': portfolio, 'testimonial': testimonial, 'blogs': blogs}
    return render(request, 'mysite/index.html', context)


def about(request):

    about_us = CMSPage.objects.filter(slug='about_us')[:1]
    context = {"about_us": about_us}
    return render(request, 'mysite/about.html', context)


def blog(request):

    blogs = Blog.objects.filter()
    context = {'blogs': blogs}
    return render(request, 'mysite/blog.html', context)


def blog_detail(request, id):
    blog_id = id
    blogs = Blog.objects.filter(id=blog_id)
    all_blogs = Blog.objects.filter().exclude(id=blog_id)
    context = {"blogs": blogs, "all_blogs": all_blogs}
    return render(request, "mysite/blog_detail.html",context)


def portfolio(request):

    portfolio = Portfolio.objects.filter()
    portfolio_category = PortfolioCategory.objects.filter()
    context = {"portfolio": portfolio, "portfolioCategory": portfolio_category}
    return render(request, "mysite/portfolio.html", context)



def contact(request):

    name = request.POST.get('name')
    email = request.POST.get('email')
    message = request.POST.get('message')

    portal_contact_email = preferences.MyPreferences.portal_contact_email

    body = "Hi, we got new inquiry from, name : "+name+', Message : '+message

    email = EmailMessage('New Inquiry', body, to=[portal_contact_email])
    email.send()

    data = {}
    data['status'] = 1
    return JsonResponse(data)

mysite/templates/mysite/about.html
{% extends "mysite/layout.html" %}
{% load static %}
{% block content %}


<!-- page title -->
<section class="page-title-alt bg-primary position-relative">
  <div class="container">
    <div class="row">
      <div class="col-12">
        <h1 class="text-white font-tertiary">About Me</h1>
      </div>
    </div>
  </div>
  <!-- background shapes -->
  <img src="{% static "mysite/images/illustrations/leaf-bg-top.png" %}" alt="illustrations" class="bg-shape-1 w-100">
  <img src="{% static "mysite/images/illustrations/dots-group-sm.png" %}" alt="illustrations" class="bg-shape-2">
  <img src="{% static "mysite/images/illustrations/leaf-yellow.png" %}" alt="illustrations" class="bg-shape-3">
  <img src="{% static "mysite/images/illustrations/leaf-orange.png" %}" alt="illustrations" class="bg-shape-4">
  <img src="{% static "mysite/images/illustrations/dots-group-cyan.png" %}" alt="illustrations" class="bg-shape-5">
  <img src="{% static "mysite/images/illustrations/leaf-cyan-lg.png" %}" alt="illustrations" class="bg-shape-6">
</section>
<!-- /page title -->

<!-- about -->
<section class="section pt-5">
  <div class="container">
    <div class="row">
      <div class="col-md-8">
            {{  about_us.0.description|safe }}
      </div>
      <div class="col-md-4 text-center drag-lg-top">
        <div class="shadow-down mb-4">
          <img src="{% static "mysite/images/about/author.jpg" %}" alt="author" class="img-fluid w-100 rounded-lg border-thick border-white">
        </div>
        <img src="{% static "mysite/images/about/signature.png" %}" alt="signature" class="img-fluid">
        <h4>Chirag Patel</h4>
      </div>
    </div>
  </div>
</section>
<!-- /about -->

<!-- Work Process -->
<section class="section">
  <div class="container">
    <div class="row justify-content-around">
      <div class="col-lg-12 text-center">
        <h2 class="section-title">Work Process</h2>
      </div>
      <div class="col-lg-3 col-md-4 text-center hover-shadow pt-3">
        <div class="">
          <img src="{% static "mysite/images/icons/plan.png" %}" class="mb-4" alt="icon">
          <h4 class="mb-4">Research and Plan</h4>
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et
            dolore magna aliqua.</p>
        </div>
      </div>
      <div class="col-lg-3 col-md-4 text-center hover-shadow pt-3">
        <img src="{% static "mysite/images/icons/design.png" %}" class="mb-4" alt="icon">
        <h4 class="mb-4">Design and Develop</h4>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et
          dolore magna aliqua.</p>
      </div>
      <div class="col-lg-3 col-md-4 text-center hover-shadow pt-3">
        <img src="{% static "mysite/images/icons/print.png" %}" class="mb-4" alt="icon">
        <h4 class="mb-4">Deliver</h4>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et
          dolore magna aliqua.</p>
      </div>
    </div>
  </div>
</section>
<!-- ./Work Process -->


{% endblock %}

mysite/templates/mysite/blog.html
{% extends "mysite/layout.html" %}
{%  load static %}


{% block content %}

    <!-- page title -->
<section class="page-title bg-primary position-relative">
  <div class="container">
    <div class="row">
      <div class="col-12 text-center">
        <h1 class="text-white font-tertiary">Blogs</h1>
      </div>
    </div>
  </div>
  <!-- background shapes -->
  <img src="{% static "mysite/images/illustrations/page-title.png" %}" alt="illustrations" class="bg-shape-1 w-100">
  <img src="{% static "mysite/images/illustrations/leaf-pink-round.png" %}" alt="illustrations" class="bg-shape-2">
  <img src="{% static "mysite/images/illustrations/dots-cyan.png" %}" alt="illustrations" class="bg-shape-3">
  <img src="{% static "mysite/images/illustrations/leaf-orange.png" %}" alt="illustrations" class="bg-shape-4">
  <img src="{% static "mysite/images/illustrations/leaf-yellow.png" %}" alt="illustrations" class="bg-shape-5">
  <img src="{% static "mysite/images/illustrations/dots-group-cyan.png" %}" alt="illustrations" class="bg-shape-6">
  <img src="{% static "mysite/images/illustrations/leaf-cyan-lg.png" %}" alt="illustrations" class="bg-shape-7">
</section>
<!-- /page title -->

<!-- blog -->
<section class="section">
  <div class="container">
    <div class="row">

        {% for blogs_data in blogs %}
        <div class="col-lg-4 col-sm-6 mb-4">
          <article class="card shadow">
            <img class="rounded card-img-top" src="{{  blogs_data.image.url }}" alt="post-thumb">
            <div class="card-body">
              <h4 class="card-title"><a class="text-dark" href="{% url "mysite:blog-detail" blogs_data.id %}">{{ blogs_data.title }}</a>
              </h4>
              <p class="cars-text">{{ blogs_data.description|slice:"0:200" |safe }}</p>
              <a href="{% url "mysite:blog-detail" blogs_data.id %}" class="btn btn-xs btn-primary">Read More</a>
            </div>
          </article>
        </div>
        {% endfor %}


    </div>
  </div>
</section>
<!-- /blog -->

{% endblock %}

mysite/templates/mysite/blog_detail.html
{% extends "mysite/layout.html" %}
{% load  static %}

{% block content %}

    <!-- page title -->
<section class="page-title bg-primary position-relative">
  <div class="container">
    <div class="row">
      <div class="col-12 text-center">
        <h1 class="text-white font-tertiary">Blogs</h1>
      </div>
    </div>
  </div>
  <!-- background shapes -->
  <img src="{% static "mysite/images/illustrations/page-title.png" %}" alt="illustrations" class="bg-shape-1 w-100">
  <img src="{% static "mysite/images/illustrations/leaf-pink-round.png" %}" alt="illustrations" class="bg-shape-2">
  <img src="{% static "mysite/images/illustrations/dots-cyan.png" %}" alt="illustrations" class="bg-shape-3">
  <img src="{% static "mysite/images/illustrations/leaf-orange.png" %}" alt="illustrations" class="bg-shape-4">
  <img src="{% static "mysite/images/illustrations/leaf-yellow.png" %}" alt="illustrations" class="bg-shape-5">
  <img src="{% static "mysite/images/illustrations/dots-group-cyan.png" %}" alt="illustrations" class="bg-shape-6">
  <img src="{% static "mysite/images/illustrations/leaf-cyan-lg.png" %}" alt="illustrations" class="bg-shape-7">
</section>
<!-- /page title -->

<section class="section">
  <div class="container">
    <div class="row">
      <div class="col-lg-12">
        <h3 class="font-tertiary mb-5">{{ blogs.0.title }}</h3>
        <p class="font-secondary">Published on {{ blogs.0.published_date|date:"d F, Y" }}</p>
        <div class="content">
          <img src="{{ blogs.0.image.url }}" style="width: 402px;" alt="post-thumb" class="img-fluid rounded float-left mr-5 mb-4">
          {{ blogs.0.description|safe }}
        </div>
      </div>
    </div>
  </div>
</section>

{#<section>#}
{#  <div class="container">#}
{#    <div class="row">#}
{#      <div class="col-lg-12">#}
{#        <h4 class="font-weight-bold mb-3">Comments 03</h4>#}
{#        <div class="bg-gray p-5 mb-4">#}
{#          <div class="media border-bottom py-4">#}
{#            <img src="{% static "mysite/images/user-1.jpg" %}" class="img-fluid align-self-start rounded-circle mr-3" alt="">#}
{#            <div class="media-body">#}
{#              <h5 class="mt-0">Carole Marvin.</h5>#}
{#              <p>15 january 2015 At 10:30 pm</p>#}
{#              <p>Ne erat velit invidunt his. Eum in dicta veniam interesset, harum fuisset te nam ea cu lupta#}
{#                definitionem.</p>#}
{#              <a href="#" class="btn btn-transparent btn-sm pl-0">Reply</a>#}
{#              <div class="media my-5">#}
{#                <img src="{% static "mysite/images/user-2.jpg" %}" class="img-fluid align-self-start rounded-circle mr-3" alt="">#}
{#                <div class="media-body">#}
{#                  <h5 class="mt-0">Jaquan Rolfson.</h5>#}
{#                  <p>15 january 2015 At 10:30 pm</p>#}
{#                  <p>Ne erat velit invidunt his. Eum in dicta veniam interesset, harum fuisset te nam ea cu lupta#}
{#                    definitionem.</p>#}
{#                  <a href="#" class="btn btn-transparent btn-sm pl-0">Reply</a>#}
{#                </div>#}
{#              </div>#}
{#            </div>#}
{#          </div>#}
{#          <div class="media py-4">#}
{#            <img src="{% static "mysite/images/user-3.jpg" %}" class="img-fluid align-self-start rounded-circle mr-3" alt="">#}
{#            <div class="media-body">#}
{#              <h5 class="mt-0">Bruce Bernier.</h5>#}
{#              <p>15 january 2015 At 10:30 pm</p>#}
{#              <p>Ne erat velit invidunt his. Eum in dicta veniam interesset, harum fuisset te nam ea cu lupta#}
{#                definitionem.</p>#}
{#              <a href="#" class="btn btn-transparent btn-sm pl-0">Reply</a>#}
{#            </div>#}
{#          </div>#}
{#        </div>#}
{#        <h4 class="font-weight-bold mb-3 border-bottom pb-3">Leave a Comment</h4>#}
{#        <form action="#" class="row">#}
{#          <div class="col-md-6">#}
{#            <input type="text" class="form-control mb-3" placeholder="First Name" name="fname" id="fname">#}
{#            <input type="text" class="form-control mb-3" placeholder="Last Name" name="lname" id="lname">#}
{#            <input type="text" class="form-control mb-3" placeholder="Email *" name="mail" id="mail">#}
{#          </div>#}
{#          <div class="col-md-6">#}
{#            <textarea name="comment" id="comment" placeholder="Message" class="form-control mb-4"></textarea>#}
{#            <button type="submit" class="btn btn-primary w-100">Send Message</button>#}
{#          </div>#}
{#        </form>#}
{#      </div>#}
{#    </div>#}
{#  </div>#}
{#</section>#}

<!-- blog -->
<section class="section">
  <div class="container">
    <div class="row">
      <div class="col-12 text-center">
        <h2 class="section-title">Similar Stories</h2>
      </div>

      {% for blog_data in all_blogs %}
          <div class="col-lg-4 col-sm-6 mb-4 mb-lg-0">
            <article class="card shadow">
              <img class="rounded card-img-top" src="{{ blog_data.image.url }}" alt="post-thumb">
              <div class="card-body">
                <h4 class="card-title"><a class="text-dark" href="{% url "mysite:blog-detail" blog_data.id %}">{{ blog_data.title }}</a>
                </h4>
                <p class="cars-text">
                    {{ blog_data.description|slice:"0:200"|safe }}
                </p>
                <a href="{% url "mysite:blog-detail" blog_data.id %}" class="btn btn-xs btn-primary">Read More</a>
              </div>
            </article>
          </div>
      {% empty %}
          <p>No similar blog found</p>
      {% endfor %}

    </div>
  </div>
</section>
<!-- /blog -->


{% endblock %}

mysite/templates/mysite/footer.html
{% load static %}


<!-- contact -->
<section class="section section-on-footer" data-background="{% static "mysite/images/backgrounds/bg-dots.png" %}">
  <div class="container">
    <div class="row" id="contact-section">
      <div class="col-12 text-center">
        <h2 class="section-title">Contact Info</h2>
      </div>
      <div class="col-lg-8 mx-auto">
        <div class="bg-white rounded text-center p-5 shadow-down" >
          <h4 class="mb-80">Contact Form</h4>
          <form name="contact_us" id="contact_us" action="{% url "mysite:contact"  %}" class="row">
            {% csrf_token %}
            <div class="col-md-6">
              <input type="text" id="name" name="name" placeholder="Full Name" class="form-control px-0 mb-4" required>
                <span class="error" id="name_error" style="display: none;">Please enter name</span>
            </div>
            <div class="col-md-6">
              <input type="email" id="email" name="email" placeholder="Email Address" class="form-control px-0 mb-4" required>
                <span class="error" id="email_error" style="display: none;">Please enter email</span>
            </div>
            <div class="col-12">
              <textarea name="message" id="message" class="form-control px-0 mb-4" required
                placeholder="Type Message Here"></textarea>
                <span class="error" id="message_error" style="display: none;">Please enter message</span>
            </div>
            <div class="col-lg-6 col-10 mx-auto">
              <button type="button" class="btn btn-primary w-100" onclick="contact()">send</button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</section>
<!-- /contact -->

<!-- footer -->
<footer class="bg-dark footer-section">
  <div class="section">
    <div class="container">
      <div class="row">
        <div class="col-md-4">
          <h5 class="text-light">Email</h5>
          <p class="text-white paragraph-lg font-secondary">{{ portal_contact_email }} </p>
        </div>
        <div class="col-md-4">
          <h5 class="text-light">Phone</h5>
          <p class="text-white paragraph-lg font-secondary">{{ portal_contact_phone }}</p>
        </div>
        <div class="col-md-4">
          <h5 class="text-light">Address</h5>
          <p class="text-white paragraph-lg font-secondary">{{ portal_contact_address }}</p>
        </div>
      </div>
    </div>
  </div>
  <div class="border-top text-center border-dark py-5">
    <p class="mb-0 text-light">Copyright @<script>
        var CurrentYear = new Date().getFullYear()
        document.write(CurrentYear)
      </script>
{#        a theme by <a href="https://themefisher.com">themefisher.com</a>#}
    </p>
  </div>
</footer>
<!-- /footer -->

<!-- jQuery -->
<script src="{% static "mysite/plugins/jQuery/jquery.min.js" %}"></script>
<!-- Bootstrap JS -->
<script src="{% static "mysite/plugins/bootstrap/bootstrap.min.js" %}"></script>
<!-- slick slider -->
<script src="{% static "mysite/plugins/slick/slick.min.js" %}"></script>
<!-- filter -->
<script src="{% static "mysite/plugins/shuffle/shuffle.min.js" %}"></script>

<!-- Main Script -->
<script src="{% static "mysite/js/script.js" %}"></script>

{% block javascript %}
  <script>

    function contact() {
           var name = $("#name").val();
           var email = $("#email").val();
           var message = $("#message").val();
           var count_error = 0;

           if(name == '') {
               $("#name_error").show();
               count_error++;
           } else {
               $("#name_error").hide();
           }

           if(email == '') {
               $("#email_error").show();
               count_error++;
           } else {
               $("#email_error").hide();
           }

           if(message == '') {
               $("#message_error").show();
               count_error++;
           } else {
               $("#message_error").hide();
           }

           if(count_error == 0) {
                $.ajax({
                    type : 'POST',
                    url : '{% url "mysite:contact" %}',
                    data : $("#contact_us").serialize(),
                    dataType : 'json',
                    success : function(msg) {
                        if(msg.status == '1') {
                            $("#name").val('');
                            $("#email").val('');
                            $("#message").val('');
                            alert("Thanks, we got your inquiry, we will revert back to you soon")
                        }
                    }
                })
           }

     }

    $("document").ready(function () {

    });
  </script>
{% endblock %}

</body>
</html>

mysite/templates/mysite/header.html
{% load static %}
<!DOCTYPE html>
<html lang="zxx">

<head>
  <meta charset="utf-8">
  <title>Kross | Portfolio Template</title>

  <!-- mobile responsive meta -->
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

  <!-- ** Plugins Needed for the Project ** -->
  <!-- Bootstrap -->
  <link rel="stylesheet" href="{% static "mysite/plugins/bootstrap/bootstrap.min.css" %}">
  <!-- slick slider -->
  <link rel="stylesheet" href="{% static "mysite/plugins/slick/slick.css" %}">
  <!-- themefy-icon -->
  <link rel="stylesheet" href="{% static "mysite/plugins/themify-icons/themify-icons.css" %}">

  <!-- Main Stylesheet -->
  <link href="{% static "mysite/css/style.css" %}" rel="stylesheet">

  <!--Favicon-->
  <link rel="shortcut icon" href="{% static "mysite/images/favicon.ico" %}" type="image/x-icon">
  <link rel="icon" href="{% static "mysite/images/favicon.ico" %}" type="image/x-icon">

</head>

<body>


<header class="navigation fixed-top">
  <nav class="navbar navbar-expand-lg navbar-dark">
    <a class="navbar-brand font-tertiary h3" href="javascript:void(0);"><img src="{% static "mysite/images/logo.png" %}" alt="Myself"></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navigation"
      aria-controls="navigation" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse text-center" id="navigation">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item active">
          <a class="nav-link" href="{% url "mysite:index" %}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url "mysite:about-us" %}">about</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url "mysite:blog" %}">Blog</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url "mysite:portfolio" %}">Portfolio</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#contact-section">Contact</a>
        </li>
      </ul>
    </div>
  </nav>
</header>

mysite/templates/mysite/layout.html
{% include "mysite/header.html" %}
{% block content %}{% endblock %}
{% include "mysite/footer.html" %}

mysite/templates/mysite/portfolio.html
{% extends "mysite/layout.html" %}
{%  load static %}


{% block content %}


    <!-- page title -->
<section class="page-title bg-primary position-relative">
  <div class="container">
    <div class="row">
      <div class="col-12 text-center">
        <h1 class="text-white font-tertiary">Portfolio</h1>
      </div>
    </div>
  </div>
  <!-- background shapes -->
  <img src="{% static "mysite/images/illustrations/page-title.png" %}" alt="illustrations" class="bg-shape-1 w-100">
  <img src="{% static "mysite/images/illustrations/leaf-pink-round.png" %}" alt="illustrations" class="bg-shape-2">
  <img src="{% static "mysite/images/illustrations/dots-cyan.png" %}" alt="illustrations" class="bg-shape-3">
  <img src="{% static "mysite/images/illustrations/leaf-orange.png" %}" alt="illustrations" class="bg-shape-4">
  <img src="{% static "mysite/images/illustrations/leaf-yellow.png" %}" alt="illustrations" class="bg-shape-5">
  <img src="{% static "mysite/images/illustrations/dots-group-cyan.png" %}" alt="illustrations" class="bg-shape-6">
  <img src="{% static "mysite/images/illustrations/leaf-cyan-lg.png" %}" alt="illustrations" class="bg-shape-7">
</section>
<!-- /page title -->

<!-- portfolio -->
<section class="section">
  <div class="container">
    <div class="row mb-5">
      <div class="col-12">
        <div class="btn-group btn-group-toggle justify-content-center d-flex" data-toggle="buttons">
          <label class="btn btn-sm btn-primary active">
            <input type="radio" name="shuffle-filter" value="all" checked="checked" />All
          </label>
            {% for category_data in portfolioCategory %}
              <label class="btn btn-sm btn-primary">
                <input type="radio" name="shuffle-filter" value="{{ category_data.title }}" />{{ category_data.title }}
              </label>
            {% endfor %}
        </div>
      </div>
    </div>
    <div class="row shuffle-wrapper">

      {% for portfolio_data in portfolio %}
      <div class="col-lg-4 col-6 mb-4 shuffle-item" data-groups='["{{ portfolio_data.category }}"]'>
        <div class="position-relative rounded hover-wrapper">
          <img src="{{ portfolio_data.image.url }}" alt="portfolio-image" class="img-fluid rounded w-100 d-block">
          <div class="hover-overlay">
            <div class="hover-content">
              <a class="btn btn-light btn-sm" href="{{ portfolio_data.url }}" target="_blank">view project</a>
            </div>
          </div>
        </div>
      </div>
      {%  endfor %}

    </div>
  </div>
</section>
<!-- /portfolio -->




{% endblock %}